[project]
name = "ai-tutorials"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.2.5",
    "pandas>=2.2.3",
    "polars>=1.28.1",
    "rich>=14.0.0",
    "smolagents>=1.14.0",
]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
    "nb-black-formatter>=1.0.1",
    "pre-commit>=4.2.0",
    "ruff>=0.11.6",
]
